Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false